version: '3.8'

services:

  db_mysql:
    image: mysql:8.0
    container_name: mysql_gestioninventario
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  usuario-service:
    build:
      context: ./usuario-service
      dockerfile: Dockerfile
    container_name: ms-usuario
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/usuario_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      - db_mysql

  reporte-service:
    build:
      context: ./reporte-service
      dockerfile: Dockerfile
    container_name: ms-reporte
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/reporte_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver

    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      - db_mysql

  proveedor-service:
    build:
      context: ./proveedor-service
      dockerfile: Dockerfile
    container_name: ms-proveedor
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/proveedor_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      - db_mysql

  producto-service:
    build:
      context: ./producto-service
      dockerfile: Dockerfile
    container_name: ms-producto
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/producto_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      - db_mysql

  notificacion-service:
    build:
      context: ./notificacion-service
      dockerfile: Dockerfile
    container_name: ms-notificacion
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/notificacion_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      - db_mysql

  inventario-service:
    build:
      context: ./inventario-service
      dockerfile: Dockerfile
    container_name: ms-inventario
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/inventario_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      - db_mysql

  despacho-service:
    build:
      context: ./despacho-service
      dockerfile: Dockerfile
    container_name: ms-despacho
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/despacho_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      - db_mysql

  compra-service:
    build:
      context: ./compra-service
      dockerfile: Dockerfile
    container_name: ms-compra
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/compra_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      - db_mysql

  bodega-service:
    build:
      context: ./bodega-service
      dockerfile: Dockerfile
    container_name: ms-bodega
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/bodega_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      - db_mysql

  auditoria-service:
    build:
      context: ./auditoria-service
      dockerfile: Dockerfile
    container_name: ms-auditoria
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/auditoria_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      - db_mysql

volumes:
  mysql_data: