version: '3.8'

services:

  db_mysql:
    image: mysql:8.0
    container_name: mysql_gestioninventario
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    # --- wena webito rey ---
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      timeout: 5s
      retries: 5
      interval: 5s

  ms-api-gateway:
    build:
      context: .
      dockerfile: ./ms-api-gateway/Dockerfile
    container_name: ms-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - usuario-service
      - reporte-service
      - proveedor-service
      - producto-service
      - notificacion-service
      - inventario-service
      - despacho-service
      - compra-service
      - bodega-service
      - auditoria-service

  usuario-service:
    build:
      context: .
      dockerfile: ./usuario-service/Dockerfile
    container_name: ms-usuario
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/usuario_service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      db_mysql:
        condition: service_healthy

  reporte-service:
    build:
      context: .
      dockerfile: ./reporte-service/Dockerfile
    container_name: ms-reporte
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/reporte_service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      db_mysql:
        condition: service_healthy

  proveedor-service:
    build:
      context: .
      dockerfile: ./proveedor-service/Dockerfile
    container_name: ms-proveedor
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/proveedor_service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      db_mysql:
        condition: service_healthy

  producto-service:
    build:
      context: .
      dockerfile: ./producto-service/Dockerfile
    container_name: ms-producto
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/producto_service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      db_mysql:
        condition: service_healthy

  notificacion-service:
    build:
      context: .
      dockerfile: ./notificacion-service/Dockerfile
    container_name: ms-notificacion
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/notificacion_service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      db_mysql:
        condition: service_healthy

  inventario-service:
    build:
      context: .
      dockerfile: ./inventario-service/Dockerfile
    container_name: ms-inventario
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/inventario_service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      db_mysql:
        condition: service_healthy

  despacho-service:
    build:
      context: .
      dockerfile: ./despacho-service/Dockerfile
    container_name: ms-despacho
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/despacho_service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      db_mysql:
        condition: service_healthy

  compra-service:
    build:
      context: .
      dockerfile: ./compra-service/Dockerfile
    container_name: ms-compra
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/compra_service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      db_mysql:
        condition: service_healthy

  bodega-service:
    build:
      context: .
      dockerfile: ./bodega-service/Dockerfile
    container_name: ms-bodega
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/bodega_service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      db_mysql:
        condition: service_healthy

  auditoria-service:
    build:
      context: .
      dockerfile: ./auditoria-service/Dockerfile
    container_name: ms-auditoria
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/auditoria_service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      db_mysql:
        condition: service_healthy

volumes:
  mysql_data: