spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/notificacion_service}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.docker.compose.enabled=false

server.port=8085