server:
  port: 8080 # Puerto base o maestro

spring:
  application:
    name: ms-api-gateway

#MrDeguito: Para no enredarme luego mejor asi

  cloud:
    gateway:
      mvc:
        routes:
          # RUTA 1: Servicio de Usuarios
          - id: ruta-usuario
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/usuarios/**

          # RUTA 2: Servicio de Reportes
          - id: ruta-reporte
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/reportes/**

          # RUTA 3: Servicio de Proveedores
          - id: ruta-proveedor
            uri: http://localhost:8083
            predicates:
              - Path=/api/v1/proveedor/**

          # RUTA 4: Servicio de Productos
          - id: ruta-producto
            uri: http://localhost:8084
            predicates:
              - Path=/api/v1/productos/**

          # RUTA 5: Servicio de Notificaciones
          - id: ruta-notificacion
            uri: http://localhost:8085
            predicates:
              - Path=/api/v1/notificaciones/**

          # RUTA 6: Servicio de Inventarios
          - id: ruta-inventario
            uri: http://localhost:8086
            predicates:
              - Path=/api/v1/inventarios/**

          # RUTA 7: Servicio de Despachos
          - id: ruta-despacho
            uri: http://localhost:8087
            predicates:
              - Path=/api/v1/despachos/**

          # RUTA 8: Servicio de Compras
          - id: ruta-compra
            uri: http://localhost:8088
            predicates:
              - Path=/api/v1/compras/**

          # RUTA 9: Servicio de Bodegas
          - id: ruta-bodega
            uri: http://localhost:8089
            predicates:
              - Path=/api/v1/bodegas/**

          # RUTA 10: Servicio de Auditorias
          - id: ruta-auditoria
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/auditorias/**